# Generated by Django 4.2.5 on 2023-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Image', models.ImageField(null=True, upload_to='images')),
                ('product_Title', models.CharField(max_length=1000)),
                ('product_price', models.IntegerField(max_length=6)),
                ('product_Description', models.CharField(max_length=10000)),
                ('product_Usage', models.CharField(max_length=10000)),
                ('product_Features', models.CharField(max_length=10000)),
                ('product_Benefits', models.CharField(max_length=10000)),
            ],
        ),
    ]
